version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  php:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
    healthcheck:
      test: ["CMD", "curl", "-s", "http://nginx", "|", "grep", "works"]
      interval: 30s
      timeout: 10s
      retries: 5